InfinityMAP/Web/Areas/admin2/Models/MandateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Areas.admin2.Models
{
    public class MandateViewModel
    {
        public int MandateId { get; set; }
        public Nullable<int> historique_HistoriqueId { get; set; }
        public Nullable<int> request_requestId { get; set; }
        public Nullable<int> resource_id { get; set; }
        public float Facture { get; set; }
        public string NomMandat { get; set; }
        public string etat { get; set; }
      

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime date_end_mandate { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime date_start_mandate { get; set; }
        public virtual HistoriqueAssignationMandatViewModel historiqueassignationmandat { get; set; }
        public virtual ResourceRequestViewModel resourcerequest { get; set; }
        public virtual ResourceViewModel resource { get; set; }
    }
}

InfinityMAP/Web/Areas/admin2/Controllers/MandateController.cs
using Domain.Entites;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OfficeOpenXml;

using Service;
using SERVICE;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using Web.Areas.admin2.Models;

namespace Web.Areas.admin2.Controllers
{
    public class MandateController : Controller
    {
        IMandateService MandatService = new MandateService();
        IHistoriqueService HistorriqueService = new HistoriqueService();
        public ActionResult viewMap()
        {

          
            return View();

        }
        // GET: admin2/Mandate
        public ActionResult Index()
        {
           
            List<MandateViewModel> liste = new List<MandateViewModel>();
         
            
            HttpClient Client= new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:18080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync("InfinityMAP-web/rest/mandate/ListeMandats").Result;
      
            if (response.IsSuccessStatusCode)
            {
               var listeMandat= response.Content.ReadAsAsync<IEnumerable<mandate>>().Result;
            
                foreach (var i in listeMandat)
                {
                    MandateViewModel userView = new MandateViewModel();
                    userView.Facture = i.Facture;
                    userView.MandateId = i.MandateId;
                    userView.NomMandat= i.NomMandat;
                    userView.date_end_mandate= i.date_end_mandate;
                    userView.date_start_mandate = i.date_start_mandate;
                    userView.etat = i.etat;
             
                    liste.Add(userView);
                }

            }
            else
            {
                liste = null;
            }
            return View(liste);

        }
    
        public ActionResult calculFactureMandat(int mandateId)
        {

            List<MandateViewModel> liste = new List<MandateViewModel>();
            List<ResourceViewModel> listeR = new List<ResourceViewModel>();
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:18080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync("http://127.0.0.1:18080/InfinityMAP-web/rest/mandate/calculFacture?mandateId="+mandateId).Result;


            return RedirectToAction("Edit/"+mandateId);

         
        }

        //public ActionResult ExportPDF()
        //{
        //    ActionAsPdf result = new ActionAsPdf("calculFactureTotale")
        //    {
        //        FileName = Server.MapPath("~/Content/Facture.pdf")

        //    };
        //    return result;
        //}


           public ActionResult calculFactureTotale()
        {

            List<mandate> liste = new List<mandate>();
            List<MandateViewModel> liste1 = new List<MandateViewModel>();
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:18080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync("http://127.0.0.1:18080/InfinityMAP-web/rest/mandate/calculFactureTotal?resourceId="+15).Result;


            if (response.IsSuccessStatusCode)
            {
                liste = MandatService.GetAll().Where(m => m.resource.id == 15).ToList();
                foreach (var i in liste)
                {
                    MandateViewModel userView = new MandateViewModel();
                    userView.Facture = i.Facture;
                    userView.MandateId = i.MandateId;
                    userView.NomMandat = i.NomMandat;
                    userView.date_end_mandate = i.date_end_mandate;
                    userView.date_start_mandate = i.date_start_mandate;
                    userView.etat = i.etat;

                    liste1.Add(userView);
                }

                if (liste != null) {
                   
                        ViewBag.Message = response.Content.ReadAsStringAsync().Result;
                }
           }
            else
            {
                ViewBag.Message = "error";
            }

            return View(liste1);
        }


        [HttpPost]
        public ActionResult Index(DateTime dateDebutMandat,DateTime dateFinMandat,string nomMandat)
        {
            List<MandateViewModel> liste = new List<MandateViewModel>();


            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:18080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync("InfinityMAP-web/rest/mandate/ListeMandats").Result;
            if (response.IsSuccessStatusCode)
            {
                var listeMandat = response.Content.ReadAsAsync<IEnumerable<mandate>>().Result;
                foreach (var i in listeMandat)
                {
                    MandateViewModel userView = new MandateViewModel();
                    userView.Facture = i.Facture;
                    userView.MandateId = i.MandateId;
                    userView.NomMandat = i.NomMandat;
                    userView.date_end_mandate = i.date_end_mandate;
                    userView.date_start_mandate = i.date_start_mandate;
                    liste.Add(userView);
                }

            }
            if (!String.IsNullOrEmpty(dateDebutMandat.ToString()) && !String.IsNullOrEmpty(dateFinMandat.ToString()) &&!String.IsNullOrEmpty(nomMandat))
            {
                liste = liste.Where(m => m.date_start_mandate.Equals(dateDebutMandat))
                    .Where(m1=>m1.date_end_mandate.Equals(dateFinMandat)).Where(m2=>m2.NomMandat.Equals(nomMandat)).ToList();


            }
        
            return View(liste);
        }

        // GET: admin2/Mandate/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin2/Mandate/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: admin2/Mandate/Edit/5

        public ActionResult Edit(int id)
        {
            List<MandateViewModel> liste = new List<MandateViewModel>();

            ResourceViewModel r = new ResourceViewModel();
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:18080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync("InfinityMAP-web/rest/mandate/ListeMandats").Result;
         
            if (response.IsSuccessStatusCode)
            {
                var listeMandat = response.Content.ReadAsAsync<IEnumerable<mandate>>().Result;
       
                foreach (var i in listeMandat)
                {
                    HttpResponseMessage response2 = Client.GetAsync("InfinityMAP-web/rest/mandate/serachResource?mandatId=" + i.MandateId).Result;

                    string responseString = response2.Content.ReadAsStringAsync().Result;
                    JObject r2 = JObject.Parse(responseString);
          
                   var s= JsonConvert.DeserializeObject<ResourceViewModel>(r2.ToString());


                    MandateViewModel userView = new MandateViewModel();
                    userView.resource = r;
                    userView.Facture = i.Facture;
                    userView.MandateId = i.MandateId;
                    userView.NomMandat = i.NomMandat;
                    userView.date_end_mandate = i.date_end_mandate;
                    userView.date_start_mandate = i.date_start_mandate;
                    r = s;
                    userView.resource= r;
                    liste.Add(userView);
                    List<mandate> m = new List<mandate>();

                    m = r.mandates.ToList();


                    ViewBag.resourceId = r.id;


                    ViewBag.data = m;
                    ViewBag.count = m.Count;


                }

            }
         
            MandateViewModel m3 = new MandateViewModel();
           m3 = liste.Find(x => x.MandateId==id);

            return View(m3);

        }

        // POST: admin2/Mandate/Edit/5
        [HttpPost]
        public ActionResult Edit(MandateViewModel mandate,int id)
        {
            mandate m = new mandate();
            m.date_end_mandate = mandate.date_end_mandate;
            m.date_start_mandate = mandate.date_start_mandate;
            m.MandateId = mandate.MandateId;
            object data = new
            {
                date_start_mandate =m.date_start_mandate,
               date_end_mandate =m.date_end_mandate
        };
        HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:18080");
            var myContent = JsonConvert.SerializeObject(data);
            var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
            var byteContent = new ByteArrayContent(buffer);
            byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

InfinityMAP/Web/Areas/admin2/Views/Mandate/Edit.cshtml
@model Web.Areas.admin2.Models.MandateViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin2/Views/Shared/_Layoutadmin2.cshtml";
}
<link href="~/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet">


<header class="pageheader hidden-xs">
    <h3><i class="fa fa-home"></i> Form Components </h3>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
            <li> <a href="#"> Home </a> </li>
            <li class="active"> form components </li>
        </ol>
    </div>
</header>
<!--Page content-->
<section id="page-content">
    <div class="row">
        <div class="col-lg-6">
            <div class="panel">
                <div class="panel-heading">
                    <div class="panel-control">
                        <button class="btn btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></button>
                        <button class="btn btn-default" data-click="panel-reload"><i class="fa fa-refresh"></i></button>
                        <button class="btn btn-default" data-click="panel-collapse"><i class="fa fa-chevron-down"></i></button>
                        <button class="btn btn-default" data-dismiss="panel"><i class="fa fa-times"></i></button>
                    </div>
                    <h3 class="panel-title">Mandates/Update Mandate</h3>
                </div>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })



                        <div class="form-group">
                            @Html.LabelFor(model => model.NomMandat, htmlAttributes: new { @class = "col-md-3 control-label" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.NomMandat, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NomMandat, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.date_end_mandate, htmlAttributes: new { @class = "col-md-3 control-label" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.date_end_mandate, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.date_end_mandate, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.date_start_mandate, htmlAttributes: new { @class = "col-md-3 control-label" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.date_start_mandate, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.date_start_mandate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Facture, htmlAttributes: new { @class = "col-md-3 control-label" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.Facture, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Facture, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-8">
                                <center><button id="demo-dt-delete-btn" class="btn btn-pink">Update</button></center>
                            </div>
                        </div>
                    </div>
                }
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    
        <div class="col-lg-3 col-sm-12 col-md-6 col-xs-12">
            <!--Profile Widget-->
            <!--===================================================-->
            <div class="panel widget">
                <div class="widget-header bg-purple">
                    <img class="widget-bg img-responsive" src="~/img/Levio.PNG" alt="Image">
                </div>
                <div class="widget-body text-center">
                    <img alt="Profile Picture" class="widget-img img-border-light" src="~/img/@Html.DisplayFor(m => m.resource.picture)">
                    <h4 class="mar-no">@Html.DisplayFor(m => m.resource.firstname)</h4>
                    <p class="text-muted mar-btm">@Html.DisplayFor(m => m.resource.profil)</p>
                  
                </div>
                <ul class="menu-items">
               

                  
@using (Html.BeginForm("calculFactureMandat", "Mandate", FormMethod.Get))
{ 
                    <li >
                        <a href="javascript:void(0)" class="clearfix">
                            <i class="fa fa-line-chart"></i> Mandates
                            <span class="label label-danger label-circle pull-right">@ViewBag.count</span>
                        </a>
                  
                   
                    <div class="col-md-6">
                        <select class="form-control" name="mandateId" id="mandateId">

                            @{


                                foreach (var item in ViewBag.data)
                                {   //using foreach
                                    <option value=@item.MandateId>@item.NomMandat</option>
                                }

                            }
                        </select>
                       
                    </div>


</li>
                    <li><button id="demo-dt-delete-btn" class="btn btn-pink" >calcul Facture</button></li>
                    }
                    <li>
                    <center>    @Html.ActionLink("View Facture Totale", "calculFactureTotale", "Mandate", new { resourceId =ViewBag.resourceId }, new { @area = "admin2" }) </center>

                    </li>
                    <li>
                        <a href="javascript:void(0)" class="clearfix">
                            <i class="fa fa-map-marker"></i>
                           View Position
                        </a>
                           
                        
                    </li>
                   
                </ul>
                <!--===================================================-->
            </div>
        </div>

    </div>
    

</section>

InfinityMAP/Web/Areas/admin2/Views/Mandate/Index.cshtml
@model IEnumerable<Web.Areas.admin2.Models.MandateViewModel>

@{
    ViewBag.Title = "list Mandates";
    Layout = "~/Areas/admin2/Views/Shared/_Layoutadmin2.cshtml";
}

              
            
 
                <div class="pageheader hidden-xs">
                    <h3><i class="fa fa-home"></i> Datatable Table </h3>
                    <div class="breadcrumb-wrapper">
                        <span class="label">You are here:</span>
                        <ol class="breadcrumb">
                            <li> <a href="#"> Home </a> </li>
                            <li class="active"> datatable Table </li>
                        </ol>
                    </div>
                </div>
                <!--Page content-->
                <!--===================================================-->
                <div id="page-content">
                    <div class="row">
                        <div class="col-md-12">

                            <!-- Basic Data Tables -->
                            <!--===================================================-->
                            <div class="panel">
                                <div class="panel-heading">
                                    <h3 class="panel-title">Liste Mandats</h3>
                                </div>
                            
                                <div class="panel-body">
                                    <table id="demo-dt-basic" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.NomMandat)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.date_start_mandate)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.date_end_mandate)
                                                </th>
                                              
                                                <th>
                                                    @Html.DisplayNameFor(model => model.Facture)
                                                </th>
                                                <th>Options</th>
                                             
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.NomMandat)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.date_start_mandate)
                                                    </td>
                                                    
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.date_end_mandate)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Facture)
                                                    </td>
                                                    

                                                    <td>
                                                        @Html.ActionLink("Edit", "Edit", "Mandate", new { id = @item.MandateId }, new { @area = "admin2" }) |
                                                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                                                        @Html.ActionLink("Delete", "Delete", "Mandate", new { mandatId = @item.MandateId }, new { @area = "admin2" })
                                                        @Html.ActionLink("historique", "historique", "Mandate", new { mandatId = @item.MandateId }, new { @area = "admin2" })
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
          
                </div>
                <!--===================================================-->
                <!--End page content-->
           
    

InfinityMAP/Web/Areas/admin2/Views/Mandate/calculFactureTotale.cshtml
@model IEnumerable<Web.Areas.admin2.Models.MandateViewModel>

@{
    ViewBag.Title = "calculFactureTotale";
    Layout = "~/Areas/admin2/Views/Shared/_Layoutadmin2.cshtml";
}


<div class="pageheader hidden-xs">
    <h3><i class="fa fa-home"></i> Datatable Table </h3>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
            <li> <a href="#"> Home </a> </li>
            <li class="active"> datatable Table </li>
        </ol>
    </div>
</div>
<!--Page content-->
<!--===================================================-->
<div id="page-content">
    <div class="row">
        <div class="col-md-12">

            <!-- Basic Data Tables -->
            <!--===================================================-->
            <div class="panel">
                <div class="panel-heading">
               
                        <h2>@ViewBag.Message</h2>
                    
                   
                </div>
                <h3 class="panel-title">Liste Mandats</h3>
                <div class="panel-body" width="50">
                    <table id="" class="table table-striped table-bordered" >
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.NomMandat)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.date_start_mandate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.date_end_mandate)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.Facture)
                                </th>
                       

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NomMandat)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.date_start_mandate)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.date_end_mandate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Facture)
                                    </td>


                               
                                </tr>
                                            }
                        </tbody>
                    </table>
                    <a href="@Url.Action("ExportPDF","Mandate")">Export Pdf</a>
                </div>
            </div>
        </div>
    </div>

</div>
<!--===================================================-->
<!--End page content-->

InfinityMAP/Web/Areas/admin2/Views/Mandate/historique.cshtml
@model IEnumerable<Web.Areas.admin2.Models.HistoriqueAssignationMandatViewModel>

@{
    ViewBag.Title = "historique";
    Layout = "~/Areas/admin2/Views/Shared/_Layoutadmin2.cshtml";
}



<div class="pageheader hidden-xs">
    <h3><i class="fa fa-home"></i> Datatable Table </h3>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
            <li> <a href="#"> Home </a> </li>
            <li class="active"> datatable Table </li>
        </ol>
    </div>
</div>
<!--Page content-->
<!--===================================================-->
<div id="page-content">
    <div class="row">
        <div class="col-md-12">

            <!-- Basic Data Tables -->
            <!--===================================================-->
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">Liste Mandats</h3>
                </div>

                <div class="panel-body">
                    <table id="demo-dt-basic" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.HeureSauvegarde)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.etatMandat)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.action)
                                </th>
                              
                          
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.HeureSauvegarde)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.etatMandat)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.action)
                                    </td>
                                    
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
<!--===================================================-->
<!--End page content-->

InfinityMAP/Web/Areas/admin2/Views/Mandate/viewMap.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Custom Markers</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
        /* Always set the map height explicitly to define the size of the div
        * element that contains the map. */
        #map {
            height: 100%;
        }
        /* Optional: Makes the sample page fill the window. */
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
    </style>
</head>
<body>
    <div id="map"></div>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 16,
          center: new google.maps.LatLng(-33.91722, 151.23064),
          mapTypeId: 'roadmap'
        });







        var features = [
          {
              position: new google.maps.LatLng(-33.91721, 151.22630)



          }
        ];

        // Create markers.
        features.forEach(function(feature) {
          var marker = new google.maps.Marker({
            position: feature.position,

            map: map,
              title:feature.title
          });
        });
      }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB9xzwsXgOhhN7tXlk5TWkjp3nKml_xiwA&callback=initMap">
    </script>
</body>
</html>