InfinityMAP/Web/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class CalendarController : Controller
    {
        // GET: Calendar
        public ActionResult Index()
        {
            return View();
        }

        // GET: Calendar/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Calendar/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Calendar/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Calendar/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Calendar/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Calendar/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Calendar/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

InfinityMAP/Web/Controllers/ResourceController.cs
using Domain.Entites;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using Service;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace Web.Controllers
{
    public class ResourceController : Controller
    {
        IResourceService rs = new ResourceService();
        IResourceRequestService rrs = new ResourceRequestService();
        // GET: Resource
        public ActionResult Index(string lastname, string firstname, string region,string contractype,string state)
        {
            string contract = "";
            List<ResourceViewModel> listResourceViewModels = new List<ResourceViewModel>();
            String url = "/InfinityMAP-web/rest/ResourceService/filterResources?";
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:18080");
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            if (!String.IsNullOrEmpty(firstname))
            {
                url = url + "&firstname=" + firstname;
            }
            if (!String.IsNullOrEmpty(lastname))
            {
                url = url + "&lastname=" + lastname;
            }
            if (!String.IsNullOrEmpty(region))
            {
                url = url + "&region=" + region;
            }
            if (!String.IsNullOrEmpty(contractype))
            {
                url = url + "&contractype=" + contractype;
                contract = contractype;
                
            }
            if (!String.IsNullOrEmpty(state))
            {
                url = url + "&state=" + state;

            }
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {

                ViewBag.result = response.Content.ReadAsAsync<IEnumerable<resource>>().Result;
                ViewBag.contract = contractype;
            }
            else
            {
                ViewBag.result = "error";
            }
            return View("Index");
        }

        // GET: Resource/Details/5
        public ActionResult Details(int id)
        {
            ResourceViewModelDetails r = new ResourceViewModelDetails();


            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:18080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync("InfinityMAP-web/rest/ResourceService/detailsResources/" + id).Result;
            HttpResponseMessage response1 = Client.GetAsync("InfinityMAP-web/rest/ResourceRequestService/getResourceRequest").Result;
            if (response.IsSuccessStatusCode)
            {

                r = response.Content.ReadAsAsync<ResourceViewModelDetails>().Result;
            }
            if (response1.IsSuccessStatusCode)
            {

                ViewBag.result = response1.Content.ReadAsAsync<IEnumerable<ResourceRequestViewModel>>().Result;
                ViewBag.number = rrs.GetresourceRequestNumber();
            }
            else
            {
                ViewBag.result = "erreur";
            }
            return View(r);

        }



        // GET: Resource/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Resource/Create
        [HttpPost]
        public ActionResult Create(ResourceViewModel r, HttpPostedFileBase ImageFile)
        {

            //string filename = Path.GetFileNameWithoutExtension(r.ImageFile.FileName);
            //string extension = Path.GetExtension(r.ImageFile.FileName);
            //filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
            //r.picture = "~/Web/Image/" + filename;
            //filename = Path.Combine(Server.MapPath("~/Web/Image/"), filename);
            //r.ImageFile.SaveAs(filename);
            if (ImageFile != null)
            {
                string filename = Path.GetFileName(ImageFile.FileName);
                string path = Path.Combine(Server.MapPath("~/Image"), filename);
                ImageFile.SaveAs(path);
                r.picture = filename;
            }
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:18080");
            client.PostAsJsonAsync<ResourceViewModel>("/InfinityMAP-web/rest/ResourceService/addResource", r).ContinueWith((postTask) => postTask.Result.EnsureSuccessStatusCode());

            return RedirectToAction("Index");

        }

        // GET: Resource/Edit/5
        public ActionResult Edit(int id)
        {

            ResourceViewModelDetails r = new ResourceViewModelDetails();

            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:18080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync("InfinityMAP-web/rest/ResourceService/detailsResources/" + id).Result;
            if (response.IsSuccessStatusCode)
            {

                r = response.Content.ReadAsAsync<ResourceViewModelDetails>().Result;

            }
            else { ViewBag.result = "erreur"; }
            return View(r);
        }

        // POST: Resource/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ResourceViewModelDetails rd, HttpPostedFileBase ImageFile)
        {
            ResourceViewModelDetails r = new ResourceViewModelDetails();
            r.id = rd.id;
            r.lastname = rd.lastname;
            r.firstname = rd.firstname;
            r.profil = rd.profil;
            r.region = rd.region;
            r.sector = rd.sector;
            r.state = rd.state;
            r.seniority = rd.seniority;
            r.contractype = rd.contractype;

            if (ImageFile != null)
            {
                string filename = Path.GetFileName(ImageFile.FileName);
                string path = Path.Combine(Server.MapPath("~/Image"), filename);
                ImageFile.SaveAs(path);
                r.picture = filename;
            }
            object data = new
            {
                lastname = r.lastname,
                firstname = r.firstname,
                profil = r.profil,
                region = r.region,
                sector = r.sector,
                state = r.state,
                seniority = r.seniority,
                contractype = r.contractype,
                picture = r.picture,

            };
            try
            {

                HttpClient client = new HttpClient();
                client.BaseAddress = new Uri("http://localhost:18080");
                var myContent = JsonConvert.SerializeObject(data);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                HttpResponseMessage response = client
                    .PutAsJsonAsync("InfinityMAP-web/rest/ResourceService/updateResource/" + id, r).Result;
                if (response.IsSuccessStatusCode)
                {
                    // Get the URI of the created resource.  
                    Console.WriteLine("modifie");
                }
                else
                {
                    ViewBag.result = "error";
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Resource/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Resource/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, ResourceViewModel r)
        {

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:18080");
            HttpResponseMessage response = client
                .PutAsJsonAsync("/InfinityMAP-web/rest/ResourceService/deleteResource/" + id, r).Result;
            if (response.IsSuccessStatusCode)
            {
                // Get the URI of the created resource.  
                Console.WriteLine(response.Headers.Location);
                Console.WriteLine("deleted");
            }
            else
            {
                ViewBag.result = "error";
            }

            return RedirectToAction("Index");

        }

        // GET: Filter
        [HttpGet]
        public ActionResult Filter(ResourceViewModelDetails rv)
        {

            string url = "/InfinityMAP-web/rest/ResourceService/filterResources";
            if (rv.firstname != "")
            {
                url = url + "&firstname=" + rv.firstname;
            }
            else
            {
                Console.WriteLine("prenom null");
            }
            if (rv.lastname != "")
            {
                url = url + "&lastname=" + rv.lastname;
            }
            else
            {
                Console.WriteLine("nom null");
            }
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:18080");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {

                ViewBag.result = response.Content.ReadAsAsync<ResourceViewModel>().Result;

            }
            else { ViewBag.result = "erreur"; }

InfinityMAP/Web/Views/Resource/Calendar.cshtml
@model List<Web.Models.vacationViewModel>
@{
    ViewBag.Title = "Calendar";
    Layout = "~/Areas/admin2/Views/Shared/_Layout.cshtml";

}


<div id="calender"></div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><span id="eventTitle"></span></h4>
            </div>
            <div class="modal-body">
                <button id="btnDelete" class="btn btn-default btn-sm pull-right">
                    <span class="glyphicon glyphicon-remove"></span> Remove
                </button>
                <button id="btnEdit" class="btn btn-default btn-sm pull-right" style="margin-right:5px;">
                    <span class="glyphicon glyphicon-pencil"></span> Edit
                </button>
                <p id="pDetails"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div id="myModalSave" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Save Event</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <input type="hidden" id="hdEventID" value="0" />
                    <div class="form-group">
                        <label>Start</label>
                        <div class="input-group date" id="dtp1">
                            <input type="text" id="txtStart" class="form-control" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                    <div class="form-group" id="divEndDate">
                        <label>End</label>
                        <div class="input-group date" id="dtp2">
                            <input type="text" id="txtEnd" class="form-control" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Type of Leave</label>
                        <select id="typeLeave" class="form-control">
                            <option value="0">Maternity</option>
                            <option value="1">Sickness</option>
                            <option value="2">Holidays</option>
                        </select>
                    </div>
                    <button type="button" id="btnSave" class="btn btn-success">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </form>
            </div>
        </div>
    </div>
</div>

<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css" rel="stylesheet" />
<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.print.css" rel="stylesheet" media="print" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />


@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

    <script>
        $(document).ready(function () {
            var selectedEvent = null;
            FetchEventAndRenderCalendar();

            function FetchEventAndRenderCalendar() {
                var url = window.location.pathname;
                var id = url.substring(url.lastIndexOf('/') + 1);
                var events = [];
                $.ajax({
                    type: "GET",
                    url: '@Url.Action("GetVacations", "Resource")',
                    data: { 'id': id },
                    dataType: "json",
                    success: function (data) {
                        $.each(data, function (i, v) {
                            var typeleave;
                            var currentTimeStart = new Date(parseInt(v.dateStart.substr(6)));
                            var currentTimeEnd = new Date(parseInt(v.dateEnd.substr(6)));
                            console.log("id resource : " + id);
                            if (v.typeLeave == 0) {
                                typeleave = "Maternity";
                            }
                            if (v.typeLeave == 1) {
                                typeleave = "Sickness";
                            }
                            if (v.typeLeave == 2) {
                                typeleave = "Holidays";
                            }
                            console.log(currentTimeStart);
                            console.log(currentTimeEnd);
                            console.log(v.id);
                            console.log(v.duree);
                            console.log(v.typeLeave);
                            console.log(typeleave);
                            console.log(v.granted);
                            if (v.granted == 0) {
                                events.push({
                                    eventID: v.id,
                                    title: typeleave,
                                    start: moment(currentTimeStart),
                                    end: moment(currentTimeEnd),
                                    description: typeleave,
                                    color: "red",

                                });
                            }
                            else {
                                events.push({
                                    eventID: v.id,
                                    title: typeleave,
                                    start: moment(currentTimeStart),
                                    end: moment(currentTimeEnd),
                                    description: typeleave,
                                    color: "blue",

                                });
                            }

                            //alert('Success' + v.dateDebut + v.id);

                        });

                        GenerateCalender(events);
                    },
                    error: function (error) {
                        alert('failed');
                    }
                })
                GenerateCalender(events);

            }

            $('#btnDelete').click(function () {
                var url = window.location.pathname;
                var id = url.substring(url.lastIndexOf('/') + 1);
                if (selectedEvent != null && confirm('Are you sure?')) {
                    $.ajax({
                        type: "POST",
                        url:'@Url.Action("DeleteEvent", "Resource")',
                        data: { 'id':id,'eventID': selectedEvent.eventID },
                        success: function (data) {
                            if (data.status) {
                                //Refresh the calender
                                FetchEventAndRenderCalendar();
                                $('#myModal').modal('hide');
                                //$('#calendar').fullCalendar('rerenderEvents');
                                //$('#calendar').fullCalendar('refetchEvents');
                            }
                            else {
                                alert("you can only delete your pending requests ")
                            }
                        },
                        error: function () {
                            alert('Failed');
                        }
                    })
                }
            });

            $('#btnSave').click(function () {
                //Validation/
                var url = window.location.pathname;
                var id = url.substring(url.lastIndexOf('/') + 1);
                if ($('#txtStart').val().trim() == "") {
                    alert('Start date required');
                    return;
                }
                if ($('#txtEnd').val().trim() == "") {
                    alert('End date required');
                    return;
                }
                else {
                    var startDate = moment($('#txtStart').val(), "DD/MM/YYYY").toDate();
                    var endDate = moment($('#txtEnd').val(), "DD/MM/YYYY").toDate();
                    if (startDate > endDate) {
                        alert('Invalid end date');
                        return;
                    }
                }

                var data = {

                    dateStart: $('#txtStart').val().trim(),
                    dateEnd: $('#txtEnd').val().trim(),
                }
                console.log(data);
                SaveEvent(data);
                // call function for submit data to the server
            })
            function SaveEvent(data) {
                console.log(data.dateStart + " " + data.end + " " + data.description + " " + data.eventID);
                var url = window.location.pathname;
                var id = url.substring(url.lastIndexOf('/') + 1);
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("SaveEvent", "Resource")',
                    data: JSON.stringify(data),
                    dataType: "json",
                    success: function (data) {
                        if (data.status) {
                            //Refresh the calender
                            FetchEventAndRenderCalendar();
                            $('#myModalSave').modal('hide');
                        }
                    },
                    error: function () {
                        alert('Failed');
                    }
                })
            }

            $('#dtp1,#dtp2').datetimepicker({
                format: 'DD/MM/YYYY'
            });

            function openAddEditForm() {
                if (selectedEvent != null) {
                    $('#hdEventID').val(selectedEvent.eventID);
                    $('#txtStart').val(selectedEvent.start.format('DD/MM/YYYY HH:mm A'));
                    $('#txtEnd').val(selectedEvent.end.format('DD/MM/YYYY HH:mm A'));
                    $('#typeleave').val(selectedEvent.description);
                }
                $('#myModal').modal('hide');
                $('#myModalSave').modal();
            }

            function GenerateCalender(events) {
                $('#calender').fullCalendar('destroy');
                $('#calender').fullCalendar({
                    contentHeight: 400,
                    defaultDate: new Date(),
                    timeFormat: 'h(:mm)a',
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'month,basicWeek,basicDay,agenda'
                    },
                    eventLimit: true,
                    eventColor: '#378006',
                    events: events,
                    eventClick: function (calEvent, jsEvent, view) {
                        selectedEvent = calEvent;
                        $('#myModal #eventTitle').text(calEvent.title);
                        var $description = $('<div/>');
                        $description.append($('<p/>').html('<b>Start:</b>' + calEvent.start.format("DD-MMM-YYYY HH:mm a")));
                        if (calEvent.end != null) {
                            $description.append($('<p/>').html('<b>End:</b>' + calEvent.end.format("DD-MMM-YYYY HH:mm a")));
                        }
                        $description.append($('<p/>').html('<b>Description:</b>' + calEvent.description));
                        $('#myModal #pDetails').empty().html($description);

                        $('#myModal').modal();
                    },
                    selectable: true,
                    select: function (start, end) {
                        selectedEvent = {
                            eventID: 0,
                            title: '',
                            description: '',
                            start: start,
                            end: end,
                            allDay: false,
                            color: ''
                        };
                        openAddEditForm();
                        $('#calendar').fullCalendar('unselect');
                    },
                    editable: true,
                    eventDrop: function (event) {
                        var data = {
                            EventID: event.eventID,
                            Subject: event.typeLeave,
                            Start: event.dateStart.format('DD/MM/YYYY'),
                            End: event.dateEnd != null ? event.end.format('DD/MM/YYYY') : null,
                            Description: event.typeLeave,
                        };
                        SaveEvent(data);
                    }
                })
            }
        })
    </script>


}

InfinityMAP/Web/Views/Resource/DetailsResource.cshtml
@model Web.Models.ResourceViewModel

@{
    ViewBag.Title = "DetailResource";
}

<h2>DetailResource</h2>

<div>
    <h4>ResourceViewModel</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.seniority)
        </dt>


        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>



    </dl>
</div>

InfinityMAP/Web/Views/Resource/Edit.cshtml
@model Web.Models.ResourceViewModelDetails

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin2/Views/Shared/_Layoutadmin2.cshtml";

}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Resource", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <h4>ResourceViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.contractype, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contractype, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contractype, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" id="ImageFile" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.profil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.profil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.profil, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.region, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.region, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.sector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.seniority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.seniority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.seniority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.state, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>